/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MainComponent(props) {
  return (
    <div className="main-container">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2a3a8189-c02b-4c1a-9dbf-15719d0d792e?apiKey=7cf0dd11538347e88354561e76f8cbd4&"
        className="img"
        alt="Main Image"
      />
      <div className="sidebar">
        <div className="sidebar-item">
          <div className="sidebar-item-content" />
          <div className="sidebar-item-content" />
        </div>
        <div className="sidebar-menu">
          <a href="#" className="sidebar-link">
            Find a Doctor
          </a>
          <a href="#" className="sidebar-link">
            Find a Location
          </a>
          <a href="#" className="sidebar-link">
            Services
          </a>
          <a href="#" className="sidebar-link">
            MyChart
          </a>
          <a href="#" className="sidebar-link">
            Pay Bill
          </a>
          <a href="#" className="sidebar-link">
            Donate
          </a>
          <a href="tel:1-844-HMH-WELL" className="sidebar-link">
            1-844-HMH-WELL
          </a>
        </div>
      </div>
      <style jsx>{`
        .main-container {
          display: flex;
          justify-content: space-between;
          gap: 20px;
        }

        @media (max-width: 991px) {
          .main-container {
            flex-wrap: wrap;
          }
        }

        .img {
          aspect-ratio: 3.35;
          object-fit: contain;
          object-position: center;
          width: 275px;
          align-items: center;
          overflow: hidden;
        }

        .sidebar {
          align-self: start;
          display: flex;
          flex-grow: 1;
          flex-basis: 0%;
          flex-direction: column;
          align-items: end;
        }

        @media (max-width: 991px) {
          .sidebar {
            max-width: 100%;
          }
        }

        .sidebar-item {
          display: flex;
          width: 398px;
          max-width: 100%;
          gap: 0px;
        }

        .sidebar-item-content {
          background-color: #fff;
          display: flex;
          width: 338px;
          height: 35px;
          flex-direction: column;
        }

        .sidebar-item-content:last-child {
          border-radius: 0px 2px 2px 0px;
          background-color: #ff5200;
        }

        .sidebar-menu {
          align-self: stretch;
          display: flex;
          margin-top: 12px;
          align-items: flex-start;
          justify-content: space-between;
          gap: 20px;
          padding: 0 20px;
        }

        @media (max-width: 991px) {
          .sidebar-menu {
            max-width: 100%;
            flex-wrap: wrap;
            justify-content: center;
          }
        }

        .sidebar-link {
          color: #0039a6;
          text-align: right;
          align-self: start;
          font: 400 15px/24px Open Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
        }

        .sidebar-link:last-child {
          white-space: nowrap;
        }
      `}</style>
    </div>
  );
}