/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="flex flex-col items-stretch">
      <div className="text-zinc-800 text-3xl leading-7 whitespace-nowrap bg-zinc-50 w-full pt-3.5 pb-9 px-4 items-start max-md:max-w-full">
        Social Media
      </div>
      <div className="w-full mt-5 max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch max-md:mt-10">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/31c04cd1-ad18-4c96-a693-34f8a6586810?apiKey=54c717f8636e46ba922cd8efa50c4277&"
                className="aspect-[0.91] object-contain object-center w-full overflow-hidden"
              />
              <div className="text-neutral-600 text-base leading-6 mt-2">
                When Michelle decided to have a second baby, she knew the odds
                were stacked against her. Michelle has Type 1...
              </div>
              <div className="text-neutral-600 text-xs leading-5 whitespace-nowrap mt-3">
                November 15, 2023
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch max-md:mt-10">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/b60a20ea-3e7f-4da2-895f-9b183aea2df1?apiKey=54c717f8636e46ba922cd8efa50c4277&"
                className="aspect-[0.91] object-contain object-center w-full overflow-hidden"
              />
              <div className="text-neutral-600 text-base leading-6 mt-2 pb-5">
                If you're ready to get back on your feet after a joint
                replacement, follow these tips to do so safely:...
              </div>
            </div>{" "}
            <div className="text-neutral-600 text-xs leading-5 whitespace-nowrap mt-3">
              November 14, 2023
            </div>
          </div>{" "}
          <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch max-md:mt-10">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/82c5a3bd-16c2-4c21-a1e5-5baec915c8fb?apiKey=54c717f8636e46ba922cd8efa50c4277&"
                className="aspect-[0.91] object-contain object-center w-full overflow-hidden"
              />{" "}
              <div className="text-neutral-600 text-base leading-6 mt-2">
                This Lung Cancer Awareness Month, know that not only smokers can
                get lung cancer. Here are some other common causes.
              </div>{" "}
              <div className="text-neutral-600 text-xs leading-5 whitespace-nowrap mt-4">
                November 14, 2023
              </div>
            </div>
          </div>{" "}
          <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <div className="flex grow flex-col items-stretch max-md:mt-10">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5212ee5-1c3f-45d8-a60c-7da800586436?apiKey=54c717f8636e46ba922cd8efa50c4277&"
                className="aspect-[0.91] object-contain object-center w-full overflow-hidden"
              />{" "}
              <div className="text-neutral-600 text-base leading-6 mt-2">
                Long before ultrasounds and wearable heartbeat monitors,
                expectant mothers and their providers relied on kick counting to
                assess fetal health....
              </div>{" "}
              <div className="text-neutral-600 text-xs leading-5 whitespace-nowrap mt-4">
                November 13, 2023
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}